### ISSUE TITLE
Feature: grids + decomposed hazard checklist

### ISSUE THREAD

**Issue by chrisbc** [GNS-Science/toshi-hazard-store#11]
a) new Source Logic trees have several thousand branches so we must decompose these and do aggregation in the cloud. 
b) we need gridded sites to produce hazard maps and for site-specific results (to nearest grid-site)

The checklist then is:

 - [x] check buildling XML from new LTB json
 - [x] publish new grids into a new configuration
 - [x] add new grid options into task config
 - [x] setup truncated decomposition for testing/tuning ( subset of full LTB set )
 - [x] TEST RUN (local, + dynamodb with multi-proc)
 - [x] validate number of rlzs per LTB (should be same as  GMPE TECT_REGS * SOURCES (In LTB) = 24 (6 Sources * 4 TECT_REGS)
 - [x] BIGGER LOCAL TEST RUN (GRD_NZ_0_1 (3600 * 1LTB => STORE multi-proc = 101 mins
 - [x] new **RLZ table** add new indexing/ fields to dynamo rlzs hash = downsample_grid, sort = grid + GTID + rlzid 
 - [x] push to new tables `store_hazard_v3 4 T3BlbnF1YWtlSGF6YXJkU29sdXRpb246MTA1MzU2 R2VuZXJhbFRhc2s6MTA1MzUz -v -c`
 - [x] Add latest GMM logic tree from Sanjay (WAIT until science team supply new config)
 - [x] new **HazardAggregation table**

### PARKED / DEFERRED
 - set up us-east-1 global table replicas
 - using AWS compute test/build subset of of sample config (local) pushing to new table (use SPLIT_TRUNCATION config)
 - ToshiAPI add update mutation for HazTask and make use of this in oq_run_hazard.py (to track hazard jobs better)
 - new **DISAGG** table we want to store dissaggs PARK
 - create an aggregation function  - 1 aggregation per  grid + GTID
