### ISSUE TITLE
POC/Arrow evaluation

### ISSUE THREAD

**Issue by chrisbc** [GNS-Science/toshi-hazard-store#61]
as we delve deeper into the EPIC #50 it becomes apparent that maybe dig0data tech like arrow can help. So, can we do this...

## basic questions
 - [x] convert THS objects into a arrow/parquet dataset that can be worked on easily using just regular FileSystemLike storage (including local and S3) 
 - [x] compare performance querying and process large task (eg hazard aggregation in THP
 - [x] enumerate the pros/cons
 - [x] is [parquet](https://github.com/apache/parquet-format) the preferred serialisation format
## Sub questions:
 - [x] can we use arrows in-memory features and/or IPC  techniques to boost performance and minimise file IO [Plasma?](https://arrow.apache.org/use_cases/)
 - [x] can we do partitioning in arrow (not just parquet) how does that work see 
 - [x] can we easily reshape datasets to optimise for different use-cases (3rd party , internal heavy compute)
 - [x] can we use [SQL-like querys](https://stackoverflow.com/questions/17005237/run-sqlite3-with-python-in-command-line)
       also [here SELECT ...](https://stackoverflow.com/questions/53863449/how-to-get-parquet-file-name-based-on-data-in-table)

## Future possibly
 - can we use [memory-mapped files](https://arrow.apache.org/docs/python/parquet.html#reading-parquet-and-memory-mapping)
 - polars ?? https://medium.com/@matteo.arellano/partitioning-polars-dataframe-on-s3-with-apache-arrow-1fa6518d23f1

**Comment by chrisbc** [comment]
completed in #62
